repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        args: ['--ignore=E501,W503,E203',
               '--max-line-length=120',
               '--max-complexity=18',
               '--select=B,C,E,F,W,T4,B9']
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
